# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211729446e709b8bd09982ebe7cd81b1130ae111fbd8eeb05074d191cf8bff631ef60ebad31d5d06c7e0fd72492e9c8f12742dd1e59047a077fc6ec3de329846

test:
  secret_key_base: a5381ffb47f8e5f2feb149d489c6404d4be2ddd2d318a8d593f6d61cdd30c986e2ffbd7fc75fc66200729ac9c831ff3b09bd04a5edc0567a7cb6bcfbd55d2f2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
